### ISSUE TITLE
Can it control the textfield's cursor display?

### ISSUE THREAD

**Issue by qky1412** [kirualex/KAPinField#11]
Default is the display of token character, no cursor shows, I wonder if it can show the cursor to imply user it's time to input the pin.

**Comment by kirualex** [comment]
for that purpose you can use the "focus" styling:
- `tokenFocusColor `
- `backFocusColor `
- `backBorderFocusColor `
We don't show the actual cursor though. I'll see about also having the option to display the actual cursor.

**Comment by kirualex** [comment]
Please checkout the `master` branch, you can now animate the currently focused token

**Comment by qky1412** [comment]
Thx for your nice work here!
