### ISSUE TITLE
4.2.0 crashes

### ISSUE THREAD

**Issue by pratik-toptal** [kirualex/KAPinField#12]
It crashes when trying to set delegate in viewDidLoad:

pinTextField.properties.delegate = self

BAD_ACCESS to properties.

Revert to 4.1.0 worked fine.

**Comment by kirualex** [comment]
I can't reproduce this issue, could you elaborate, maybe provide a fix?

**Comment by pratik-toptal** [comment]
Can't reproduce it after clean build.

Thanks @kirualex for quick revert.
