### ISSUE TITLE
Did finish delegate method called only once

### ISSUE THREAD

**Issue by danqing** [kirualex/KAPinField#16]
It looks like the did finish delegate method is called only once in the following scenario:

1. Enter 1234 -> method called with 1234
2. Backspace (become 123)
3. Enter 5 (become 1235) -> method not called again

I think since backspace is allowed, the delegate method should be fired every time it's finished.

**Comment by danqing** [comment]
https://github.com/kirualex/KAPinField/blob/ef1caa4438185c3c05ec5044e718da527d9b25bc/KAPinField/Sources/KAPinField.swift#L512

This seems intentional - is there a reason?

**Comment by kirualex** [comment]
yes, there actually was an issue where it was called twice, I'll need to tweak this

**Comment by kirualex** [comment]
Could you try again?

**Comment by kevinrenskers** [comment]
The new version works a lot better! Not sure why you're sending the delegate callback when the input isn't valid? But yeah it's easy enough to ignore invalid input so it's fine :)

FYI, my code now looks something like this which still feels a bit verbose:

```
class PhoneValidationViewController: UIViewController {
  let viewModel = PhoneValidationViewModel()

  override func viewDidLoad() {
    // ...
    viewModel.code.map { $0.count == 4 }.bind(to: nextButton.reactive.isEnabled)
  }
}

extension PhoneValidationViewController: KAPinFieldDelegate {
  func pinField(_ field: KAPinField, didFinishWith code: String) {
    viewModel.code.value = code
  }

  func pinField(_ field: KAPinField, didChangeTo string: String, isValid: Bool) {
    if isValid {
      viewModel.code.value = string
    }
  }
}
```

As you can see, it's a bit annoying to have to implement both delegate methods and ignore invalid input in that second one. But hey, it works! :)

**Comment by kirualex** [comment]
The invalid callback allows you to display some feedback to the user (textfield shaking, hint message...).
I'm going to close this issue and make a new version soon.

**Comment by kevinrenskers** [comment]
Cool, makes sense.

**Comment by kevinrenskers** [comment]
I found a bug with the `didChangeTo` callback. If I set the `numberOfCharacters` to 6 for example and begin to type 1 to 6, and then continue to type, it keeps calling the `didChangeTo` method:

```
func pinField(_ field: KAPinField, didChangeTo string: String, isValid: Bool) {
    print("string: \(string)")
}

string: 1
string: 12
string: 123
string: 1234
string: 12345
string: 123456
string: 1234567
string: 1234568
string: 1234569
```

**Comment by kevinrenskers** [comment]
It should either update the 6th character or simply ignore it, force the user to use the backspace first. I could make a case for both options :)
