### ISSUE TITLE
Receiving Fatal error: Index out of range 

### ISSUE THREAD

**Issue by Chesong-Lee-Hospii** [kirualex/KAPinField#19]
Getting `Fatal error: Index out of range` on this line `let backView = self.backViews[backIndex]`

I am creating `KAPinField` programmatically and within my code I have `securityCodeTextField` which is type `KAPinField`.

Within my code I am setting:

```
securityCodeTextField.appearance.tokenColor = UIColor.blue.withAlphaComponent(0.2)
securityCodeTextField.appearance.tokenFocusColor = UIColor.blue.withAlphaComponent(0.2)
securityCodeTextField.appearance.textColor = UIColor.blue
securityCodeTextField.appearance.font = .menlo(40)
securityCodeTextField.appearance.kerning = 24
securityCodeTextField.appearance.backOffset = 5
securityCodeTextField.appearance.backColor = UIColor.clear
securityCodeTextField.appearance.backBorderWidth = 1
securityCodeTextField.appearance.backBorderColor = UIColor.blue.withAlphaComponent(0.2)
securityCodeTextField.appearance.backCornerRadius = 4
securityCodeTextField.appearance.backFocusColor = UIColor.clear
securityCodeTextField.appearance.backBorderFocusColor = UIColor.blue.withAlphaComponent(0.8)
securityCodeTextField.appearance.backActiveColor = UIColor.clear
securityCodeTextField.appearance.backBorderActiveColor = UIColor.blue
securityCodeTextField.appearance.backRounded = false
```

**Comment by kirualex** [comment]
can you try on the latest  commit of `master` branch? I can't seem to reproduce your issue. What about the properties for your `securityCodeTextField `?

**Comment by Chesong-Lee-Hospii** [comment]
That's the only property. I'm using version '~> 4.2.0'. Due to an urgency, I ended up creating my own.

**Comment by ErAshu** [comment]
Fatal error: Index out of range

I got this issue in latest example. 

in the light segment, first fill all the field (wrong text)  and clear all the field. Then press refresh code and its crash.

**Comment by Dfmarulanda** [comment]
Same here.

**Comment by hesham92** [comment]
I have the same issue Fatal error: Index out of range

**Comment by kirualex** [comment]
I'll need a crashlog and/or a sample of crashing code to fix this

**Comment by Dfmarulanda** [comment]
It's simple. This happens only if you're styling your KAPinField before creating the KAPinField properties. You have to create first the properties before styling the field.

**Comment by kirualex** [comment]
@Dfmarulanda a PR would be appreciated if you already can reproduce the issue, as I can't and have a limited time for this.

**Comment by acidlynx** [comment]
@kirualex Hello! I did PR for fix this issue. Check it please.

**Comment by kirualex** [comment]
new release 5.0.1 with fix
