### ISSUE TITLE
Objective-c support

### ISSUE THREAD

**Issue by arashetm** [kirualex/KAPinField#20]
How could I use all features in objective-c?

**Comment by kirualex** [comment]
Using Cocoapods you just have to declare `use_frameworks!` in your Podfile.
Else, you can have a look here : https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_swift_into_objective-c

**Comment by arashetm** [comment]
Thanks for the reference.
I want to import your library in my project manually (without Cocoapods) and also I know what should I do for importing swift in obj-c but there are some methods and properties that could not convert to objective-c via @objc flag.
What should I do now?
