### ISSUE TITLE
SPM support with Xcode 11?

### ISSUE THREAD

**Issue by danqing** [kirualex/KAPinField#21]
I see that there's a Package.swift file, but I can't seem to use it in Xcode 11's UI:

<img width="612" alt="Screen Shot 2019-10-03 at 11 37 08 PM" src="https://user-images.githubusercontent.com/5134133/66141707-b8872d80-e636-11e9-943a-887b3fff16f9.png">

Am I missing something? Thanks!

**Comment by che1404** [comment]
Same here. 
Any progress on this?

Thanks!
