### ISSUE TITLE
add editingChanged target

### ISSUE THREAD

**Issue by negar95** [kirualex/KAPinField#30]
Hi, thanks for this great pinfield
I need to change every input to persian number
I implement a convertNumbersToPersian in string extension
for normal textFields I use
TextField.addTarget(self, action: #selector(textFieldDidChange(sender:)), for: .editingChanged)
and
@objc func textFieldDidChange(sender: UITextField) {
        sender = sender.text?.convertNumberToPersian()
}
how is it possible to do something like this in KAPinField?
thanks

**Comment by kirualex** [comment]
hmm this is an interesting issue, maybe an idea would be to provide a datasource callback to allow input handling, although I'm not sure how exactly it would fit in yet

**Comment by negar95** [comment]
I can do this. :)

**Comment by negar95** [comment]
yes
and also it should accept Persian/Arabic characters
