### ISSUE TITLE
Capitalization not working

### ISSUE THREAD

**Issue by aabanaag** [kirualex/KAPinField#31]
Setting capitalization to All Characters doesn't work. Whenever I set it to All Characters the keyboard is still in lowercased.

**Comment by kirualex** [comment]
yes this would need a specific overload in the library

**Comment by aabanaag** [comment]
@kirualex, I created a PR to possibly support this. https://github.com/kirualex/KAPinField/pull/32

**Comment by aabanaag** [comment]
Do I need to bump the podspec version for this to reflect?
