### ISSUE TITLE
KAPinField  clipboard notifications 

### ISSUE THREAD

**Issue by summonerriftofficial** [kirualex/KAPinField#35]
I discover that every time I try to write a letter the clipboard notification from iOS 14 is showing up 
and after a lot of  investigate, I found that the  issue with this 

//        if (UIPasteboard.general.string == self.invisibleText && isRightToLeft) {
//            self.invisibleField.text = String(self.invisibleText.reversed())
//        }

just  comment these lines and  it will  solve the problem

**Comment by kirualex** [comment]
Yes this is something related to Right-to-Left scripts regions. Unsure how to properly handle this but for now, commenting those lines is the easiest.

**Comment by svenresch** [comment]
Ran into this problem and appreciate that commenting out those lines is a workaround. Would supporting this with a new settable flag be acceptable until something else is figured out @kirualex?

**Comment by kirualex** [comment]
I actually can't reproduce this issue right now, any idea why ?
