### ISSUE TITLE
Could not use KAPinField

### ISSUE THREAD

**Issue by haroldogtf** [kirualex/KAPinField#4]
I could not user this pod getting this error:
I am using Swift 4.2, Xcode 10, iOS minimum version 10.

> [!] CocoaPods could not find compatible versions for pod "KAPinField":
>   In Podfile:
>     KAPinField
> 
> Specs satisfying the `KAPinField` dependency were found, but they required a higher minimum deployment target.

**Comment by kirualex** [comment]
minimum version is 10.3
