### ISSUE TITLE
Need support for Arabic version 

### ISSUE THREAD

**Issue by maulik6994** [kirualex/KAPinField#5]
Where text will filled from right to left.

**Comment by kirualex** [comment]
Hi @maulik6994 , this is an interesting issue. 
I tried something with 06b2b8f7cdcba81c8dd1467cd75e23ec2043c2d0
Could you pull the source from that commit and test it on your side to check if it behave as expected?

**Comment by maulik6994** [comment]
Okay I'll let you know @kirualex.

**Comment by maulik6994** [comment]
It's work perfect but return string should be also from right to left. Still getting left to right.

**Comment by kirualex** [comment]
Hey, I did some changes if you could check those out. Ideally a pull request from you would be very much appreciated, as I don't really have the proper cultural background to understand the ins-and-out of what's expected for a user here.
I'm just using the right-to-left pseudolanguage option in my project scheme to simulate it, but that might not be enough.

**Comment by kirualex** [comment]
Closing for being idle

**Comment by ahmedsafadii** [comment]
didn't fix  yet same problem

Like if I enter "123456", I am getting "654321" when for this textfield.

**Comment by ahmedsafadii** [comment]
@kirualex
