### ISSUE TITLE
support borders settings

### ISSUE THREAD

**Issue by JeankyWang** [kirualex/KAPinField#7]
I want set borders for every chars, can you add this func ?

**Comment by kirualex** [comment]
could you provide an image of what you mean?

**Comment by JeankyWang** [comment]
![image](https://user-images.githubusercontent.com/7403509/55707484-4383c400-5a16-11e9-8835-63c232d24825.png)

**Comment by JeankyWang** [comment]
![14_03_17__04_08_2019](https://user-images.githubusercontent.com/7403509/55707574-7c239d80-5a16-11e9-9f20-a5053dd49bee.jpg)

**Comment by kirualex** [comment]
you can try out the `backviews` branch, there is some styling you can use in your project.

```
        pinField.ka_backOffset = 8
        pinField.ka_backColor = UIColor.clear
        pinField.ka_backBorderWidth = 1
        pinField.ka_backBorderColor = UIColor.white.withAlphaComponent(0.3)
        pinField.ka_backCornerRadius = 4
        pinField.ka_backFocusColor = UIColor.clear
        pinField.ka_backBorderFocusColor = UIColor.white
        pinField.ka_backActiveColor = UIColor.clear
        pinField.ka_backBorderActiveColor = UIColor.white
```

I'm thinking about bringing it in the `master` branch once it'll be clean .

**Comment by JeankyWang** [comment]
OK， thks
